language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.7"
before_install:
  - chmod +x push.sh
install:
  - sudo apt-get update
  - sudo apt-get install pandoc
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install packages
  - conda create -q -n autogis-environment python=$TRAVIS_PYTHON_VERSION sphinx==1.7.9 sphinx_rtd_theme nbsphinx==0.4.3 IPython==6.5.0 jupyter_client ipykernel matplotlib geopandas
  - source activate autogis-environment
  - pip install git+https://github.com/HTenkanen/sphinxcontrib-versioning.git
  - pip install sphinxcontrib-googleanalytics
  
script: sphinx-versioning build source build/html
after_success:
  - ./push.sh
env:
  global:
    - secure: "afw1mck3R2tTumQyy1xg7o1Aw/ceNT4YOg2Uhr8m5UukTq4hyrGSPlmSPLNAMzoIiEmxqf7ubuy78hn4T0Gk3JrjyKWfxtamdaPqXG+CjGtMNnGpgfz4+wJsWAbZuz7tnxEDG6za1nPHQ3bvmWfvMFyMqL473irHZ87HKohja7XYijXE3Z4QjDgCh+Ezd+SrCQGYBqCN7v2hiAFCwFYEoHz6TBl67j8kx1kkWtFZuKMFN4cIwLCebAksZH9Q34yFHMdAeaHw7ywU5VA5EgzdIMp26neiacfhuXTw74Dg46qRccImmx8wS1roT0L6fdbiCrmfzkoHUioBqbH4hO7Fv1G/T6v8Cor4FEdiabKP0en2HFhEquK8PGrId1EtEyoUNGNIQ/fMvRAliAfEof49z8rZethL9aihtJHpbbdqhPsMlLN0niwr+XsKh9tvzIGYjCAD4e3Raqs9SiTpguiq12Io4gUCQbahVKG7u4hDDyzj5DWroiXHEc83Xy+Zya8nMLLVRJq0TrOlRRtwhTIwr+5vMJkfoC41mV3t0eoDudeBiWUA+ohjTWKdnlkukuHMaEkCG0sgpqD+pO5D4jQrQ1l2BWF+rakzsELbsprPTlXTEUiRPCEZektO4/uykwyMFpeIsMnf1h+C6CM1Y7x1vSKSwKmIUD06xKD8zg5w9+A="
