name: gis

channels:
  - conda-forge
dependencies:
  - python=3.5
  - geopandas
  - geopy
  - bokeh
  - contextily
  - matplotlib
  - folium
  - mplleaflet
  - geoplot
  - pip:
    - git+https://github.com/mullenkamp/PyCRS
